### ISSUE TITLE
IV-Stats screen is broken 

### ISSUE THREAD

**Issue by Nilssteingraeber** [lhearachel/plat-engine#76]
When opening the IV-stats screen in a PC-Box, then switching to another page and then back to the IV-stats screen, the health of the viewed pokemon becomes 0. Fixes itself upon viewing another pokemon.

![Animation](https://github.com/lhearachel/plat-engine/assets/22717175/cfd3cc73-0726-47c5-a48f-db5ab19b27e4)

**Comment by lhearachel** [comment]
Fixed by https://github.com/lhearachel/plat-engine/commit/d4e988a5dcad5c64edaa70067bbb18524558faaa
